### ISSUE TITLE
failed to legalize to lhlo operation 'mhlo.fusion' that was explicitly marked illegal

### ISSUE THREAD

**Issue by lipracer** [tensorflow/mlir-hlo#15]
There are comments in hlo_legalize_to_lhlo.cc about mhlo.fusion but it is not processed. fusionOp has defined in lhlo.td.

**Comment by joker-eph** [comment]
Can you expand on what you're trying to achieve and how you got this error message?
You may have assembled a pipeline that isn't really supported at the moment, or you found a bug, I can't tell :)

If you can provide a complete reproducer, it'd help.

**Comment by lipracer** [comment]
Just mhlo.fusion to lhlo.fusion conversion, I found discussion about them: https://github.com/tensorflow/tensorflow/issues/45820 I'am confused now whether this is a bug or designed like this.
