### ISSUE TITLE
Support Converting TF dialect to HLO dialect entirely?

### ISSUE THREAD

**Issue by Jackwin** [tensorflow/mlir-hlo#24]
Hi folks,

I'm converting the TF mode to HLO dialect based on the Tensorflow framework. The conversion sequence can be described as pbtxt -> executor -> function
`
tf-mlir-translate -graphdef-to-mlir -tf-enable-shape-inference-on-import=false saved_model.pbtxt -o resnet_50.mlir
tf-opt -tf-executor-to-functional-conversion resnet_50.mlir -o resnet_50-func.mlir
`
However, when converting from TF dialect to HLO further via the `tf-to-hlo-pipeline`, the type in TF seems not to match with that in MHLO.

>lenet_tf_launch_gpu.mlir:49:14: error: 'mhlo.dynamic_broadcast_in_dim' op operand #0 must be tensor of floating-point or pred (AKA boolean or 1-bit integer) or 8/16/32/64-bit signless integer or 8/16/32/64-bit unsigned integer or complex type with 32-bit float or 64-bit float elements values, but got 'tensor<32x!tf_type.f32ref>'
        %1 = "tf.BiasAdd"(%outputs_18, %outputs_12) {data_format = "NHWC"} : (tensor<?x?x?x32xf32>, tensor<32xf32>) -> tensor<?x?x?x32xf32>
             ^
lenet_tf_launch_gpu.mlir:49:14: note: see current operation: %38 = "mhlo.dynamic_broadcast_in_dim"(%6#0, %37) {broadcast_dimensions = dense<3> : tensor<1xi64>} : (tensor<32x!tf_type.f32ref>, tensor<4xindex>) -> tensor<?x?x?x32xf32>

So, my question is that TF dialect can be lowered to HLO entirely until now？ Or any advice about how to convert a model to HLO dialect?

Thanks

**Comment by joker-eph** [comment]
You version of Resnet seems to be using reference variable, I don't think these have even been supported in TensorFlow when using XLA. They also have been deprecated in TensorFlow for many years, any chance you could be using resource variables instead?

**Comment by Jackwin** [comment]
Yes, it is okay to use resource variables. Could you please give me a link? Now I just would like to demonstrate the translation from the a TF model to MHLO dialect,  I thought it was ready before, but it seems not to work now. After MHLO, more work will be focused on the MLIR infrastructure.  

Alternatively, do you have any suggestion of how to port to MLIR from the AI framework, such as TensorFlow and PyTorch?

**Comment by stellaraccident** [comment]
Interfacing from PyTorch is happening in a dedicated project that you can track/participate in: https://github.com/llvm/torch-mlir

It is early for that but they have e2e full models for ResNet and BERT either working or close to working. If you ask there, they can likely give you some commands to run easily to get what you need (with the caveat that it is end of year holidays for a lot of the contributors right now).

**Comment by Jackwin** [comment]
@stellaraccident  Many thanks for your reply, quite helpful.
