### ISSUE TITLE
Did the mhlo::Operation's trait of RecursiveSideEffects is necessary such as mhlo::ReduceOp SelectAndScatter and some ops with computation body.

### ISSUE THREAD

**Issue by lipracer** [tensorflow/mlir-hlo#28]
Futhur more some control flow ops like while. I refer to the implementation of HLO instructions . They are also no side effect. I think they ensure the form of SSA when constructing, which is helpful for our optimization.

**Comment by joker-eph** [comment]
HLO should be side-effect free, but technically one could do load/store inside the body of the computation region attached to a reduce op, which is what the trait indicates.

I'm not sure if I totally followed what you're asking about though?

**Comment by lipracer** [comment]
I want to know that after defining the trait, the op will be erase safely if there is no user. It seems so.I found the [mlir interface](https://github.com/llvm/llvm-project/blob/0e0e381a1547c641a54b2131665d8a38855371b4/mlir/lib/Interfaces/SideEffectInterfaces.cpp#L40).thanks.

**Comment by joker-eph** [comment]
Yes the RecursiveSideEffects traits indicates to the framework that the op is side-effect free iff the ops inside the region body are.

**Comment by lipracer** [comment]
Maybe we need to enrich the mlir docment. we can't found the description of the RecursiveSideEffects. [Traits](https://mlir.llvm.org/docs/Traits/)

**Comment by joker-eph** [comment]
Thanks! We should update our docs indeed.

That said it is a bit confusing because there are "core traits" which is what this page you're linking to, and there are other traits that are specific to some interfaces, and this is one such case. We should document these interfaces in more details!
