### ISSUE TITLE
missing test case after remove disc

### ISSUE THREAD

**Issue by lipracer** [tensorflow/mlir-hlo#32]
Would we remove this file [mhlo_fusion.cc](https://github.com/tensorflow/mlir-hlo/blob/master/lib/Dialect/mhlo/transforms/mhlo_fusion.cc) ?

**Comment by burmako** [comment]
Thank you for the ticket! Indeed, this pass is unused now after the recent removal of DISC from the repo. We'll clean this up shortly.

**Comment by lipracer** [comment]
Are upstream or downstream dependent on this pass? If not, I can remove it.

**Comment by burmako** [comment]
Earlier today, @joker-eph has put together a patch in our internal code review system, so I expect that it'll land soon and will get propagated back to GitHub. Thank you for your kind offer though :)

**Comment by lipracer** [comment]
Thanks.

**Comment by joker-eph** [comment]
Pushed in 74ca70f6ec6b58b47f83949a7d2910db1cef357f
