### ISSUE TITLE
'mhlo/IR/hlo_ops.h' file not found

### ISSUE THREAD

**Issue by gargaroff** [tensorflow/mlir-hlo#52]
Hi there,

we're using mlir-hlo in a downstream project as a submodule and include it into our project using `add_subdirectory(third_party/mlir-hlo EXCLUDE_FROM_ALL)`.

We're trying to update to the green commit from Nov. 14th, but we're hitting the error mentioned in the title: `'mhlo/IR/hlo_ops.h' file not found`.

We're linking against the following libraries:

```cmake
target_link_libraries(${TARGET} PUBLIC
  # ...
  ChloOps
  HloOpsCommon
  MLIRMhloUtils
  MhloDialect
  MhloRegisterDialects
  StablehloAssemblyFormat
  StablehloBase
  StablehloBroadcastUtils
  StablehloOps
  StablehloRegister
  StablehloTypeInference
)
```

I would assume that the MHLO include directories are propagated through the libraries we link against. Interestingly enough, `mlir_hlo/include` and `mlir_hlo/stablehlo` are are on the include path. Is there anything we're missing to get the missing include directories?

**Comment by sdasgup3** [comment]
I hope that you have `target_include_directories` correctly placed.
Can you share a bit more? Like the CMakeLists.txt file or project repo?

**Comment by gargaroff** [comment]
I didn't use `target_include_directories` before and it was working, so I assumed that it would still work without it. In the meantime, I looked at other projects using `mlir-hlo` and saw that they had to add `include_directories(third_party/mlir-hlo)` in their project to make the includes work.

If that is the intended solution, then that's ok. To me it feels like a workaround, however. I am used to CMake projects properly propagating their include directories, when you link against their libraries. For example, when I link against `MhloDialect`, I would expect that all include directories that are required to use this library, are propagated by CMake. AFAIU this should normally happen automatically through CMake when doing like this:

```cmake
# in external project
# Include directories are attached to a specific target, allowing CMake to propagate them to external users
target_include_directories(ExternalLib PUBLIC path/to/includes)

# in my project
# By linking against ExternalLib, CMake knows to add the include directories of the library, as they are required to build it
target_link_libraries(MyTarget PRIVATE ExternalLib)
```

So, I'm wondering if this is actually something that should be fixed in `mlir-hlo`? Please correct me if I'm wrong about this.

**Comment by christopherbate** [comment]
Since the directory structure was changed, there is also an incorrect include path getting attached to the `MhloDialect` target using the LLVM_EXTERNAL_PROJECTS method of building. 

When looking at the build commands generated for any of my targets depending on `MhloDialect`, I get

```
-I<build dir path>/llvm-project/llvm/tools/mlir-hlo/include
```

Which doesn't exist anymore after the directory reorg. The "include" needs to be removed.

I think the problem are these lines in `mhlo/IR/CMakeLists.txt`:

```
target_include_directories(MhloDialect
  PUBLIC
  $<BUILD_INTERFACE:${MLIR_HLO_GEN_INCLUDE_DIR}>
  $<BUILD_INTERFACE:${MLIR_HLO_MAIN_INCLUDE_DIR}>
)
```

These variables are probably getting an automatic `include` attached to them. It doesn't show up in `mli-hlo` build because there's a n `include_directories(` somewhere that prevents the issue from showing up until you build it as a dependency.

**Comment by christopherbate** [comment]
@gargaroff Here's a small snippet that may fix your problem. Works for me with LLVM_EXTERNAL_PROJECT build. You would insert this at the location where you  `target_link_libraries` against `MhloDialect`:

```cmake
# Fix include directories until https://github.com/tensorflow/mlir-hlo/issues/52 is fixed.
get_target_property(mhlo_includes_ MhloDialect INTERFACE_INCLUDE_DIRECTORIES)
list(TRANSFORM mhlo_includes_ REPLACE "mlir\-hlo/include" "mlir-hlo")
set_target_properties(MhloDialect PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${mhlo_includes_}")
```

**Comment by ddunl** [comment]
Hello, @gargaroff and @christopherbate, wondering if https://github.com/tensorflow/mlir-hlo/commit/956f751dc7602557373a0c66cdbd75bff5f3440a fixes this issue for you.

**Comment by gargaroff** [comment]
Thanks @ddunl! The changes look like they might work. It's gonna be a while until I can verify this, as we probably won't do another internal version bump before the next year, but I'll raise it with the team. Maybe somebody can check it a bit earlier

**Comment by christopherbate** [comment]
@ddunl I apologize for not responding earlier. This issue can indeed be closed, but now there is a new issue I filed at #57 . Thanks!
