### ISSUE TITLE
[cmake build] MhloDialect target no longer carries correct binary include dir 

### ISSUE THREAD

**Issue by christopherbate** [tensorflow/mlir-hlo#57]
After [this latest change to mlir-hlo/mhlo/CMakeLists.txt](https://github.com/tensorflow/mlir-hlo/commit/72cec6c13c1d44e374ac2c70fb3427fc6f6019e7#diff-c44b4f0c85511c19a545839519a13d20a54fbd78991f9843d13116988207abe1L7), the MhloDialect target no longer has the correct binary include directories attached to its INTERFACE_INCLUDE_DIRECTORIES. I now have to do the following in my downstream project when building `mlir-hlo` via the "LLVM External Project" route:

```
get_target_property(mhlo_includes_ MhloDialect INTERFACE_INCLUDE_DIRECTORIES)
list(APPEND mhlo_includes_ $<BUILD_INTERFACE:${LLVM_BINARY_DIR}/tools/mlir-hlo>)
set_target_properties(MhloDialect PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${mhlo_includes_}")
```

Otherwise, the build will fail on downstream targets that depend on `MhloDialect`. The compiler will say:

```
 fatal error: 'mhlo/IR/hlo_ops_enums.h.inc' file not found
```

Note that this is  different from #52 (which probably can now be closed).

Edit: fixed the workaround

**Comment by burmako** [comment]
Hi @christopherbate! Thank you for reporting. 
@ddunl Can you take a look please?

**Comment by ddunl** [comment]
Thanks for bringing this to my attention! @christopherbate can you let me know if https://github.com/tensorflow/mlir-hlo/commit/d39188774da0fd07ffe27687fa4eb16666a39ec2 fixes this?

**Comment by christopherbate** [comment]
@ddunl Thanks for your response. This actually doesn't fix it (in LLVM External Project mode). 

I added a print statement like this:

```
message(WARNING "MHLO DIRS: ${MLIR_HLO_SOURCE_DIR} ${MLIR_HLO_GEN_INCLUDE_DIR}")
target_include_directories(MhloDialect
  PUBLIC
  $<BUILD_INTERFACE:${MLIR_HLO_SOURCE_DIR}>
  $<BUILD_INTERFACE:${MLIR_HLO_GEN_INCLUDE_DIR}>
)
```

and `MLIR_HLO_GEN_INCLUDE_DIR` points to something like "build/llvm/tools/mlir-hlo/include" but actually the build tree under `build/llvm/tools/mlir-hlo` doesn't have an `include` directory.

**Comment by ddunl** [comment]
Ah I was clearly not being careful enough when I made that change. I'll test a fix more thoroughly tomorrow. So sorry this is taking so long to get resolved!

**Comment by ddunl** [comment]
Woops, didn't intend for this to be closed. Let me know if a170d81 fixes this.
