### ISSUE TITLE
Inclusive language (sanity -> safety)

### ISSUE THREAD

**Issue by cjvolzka** [tensorflow/mlir-hlo#60]
With moves towards inclusive language:
https://www.ibm.com/blogs/think/2020/08/words-matter-driving-thoughtful-change-toward-inclusive-language-in-technology/
we'd like to request references to "sanity" be changed to "safety" or another more inclusive term. Sanity isn't an inclusive term for those coming from neurodiverse backgrounds. 

The two hits we find are at:
* https://github.com/tensorflow/mlir-hlo/blob/master/gml_st/transforms/vectorization/vectorize_for_gpu.cc#L304
* https://github.com/tensorflow/mlir-hlo/blob/master/gml_st/transforms/vectorization/vectorize_for_gpu.cc#L350

**Comment by sherhut** [comment]
Thank you for highlighting this. This repository does not accept changes, so we will need to address this over in the https://github.com/openxla/xla repository. Have you already worked on a change? Just to not duplicate work.

**Comment by cjvolzka** [comment]
Thanks for taking a look! 
I have not started a PR against the [openxla/xla](https://github.com/openxla/xla) repo. I wasn't sure about the mechanism to pull it back to this repo afterward.

**Comment by sherhut** [comment]
This should now be changed.

For reference, the process is to make changes to the [openxla/xla](https://github.com/openxla/xla) repository and these get automatically synced back here. In essence, this is a read-only view into a part of the xla repository.

**Comment by cjvolzka** [comment]
Awesome! Thanks for the info and the quick turn around!
