### ISSUE TITLE
32-bit erf is inaccurate for x > 1

### ISSUE THREAD

**Issue by atondwal** [tensorflow/mlir-hlo#62]
see openxla/stablehlo#1238

**Comment by atondwal** [comment]
fixed by https://github.com/tensorflow/mlir-hlo/commit/3ad5e21dfce9819f30194e33933a6a225eb66f8d

**Comment by atondwal** [comment]
In practice looks like this is too slow for some users. For the 64-bit version we're fine with the performance hit of the additional select, but for the 32-bit version maybe we should just clamp it? What do you think, @jakevdp?

**Comment by atondwal** [comment]
I think @rmlarsen is taking a look

**Comment by rmlarsen** [comment]
I probably won't get to it this week, though.

**Comment by rmlarsen** [comment]
FWIW: The originally bug report is incorrect. The erc implementation is indeed very accurate, but fails to clamp the output to [-1:1].

**Comment by rmlarsen** [comment]
I'll send a CL with the clamping.

**Comment by atondwal** [comment]
(fixed by https://github.com/tensorflow/mlir-hlo/commit/29e975a3c0a469c41fc564c36766217aef9d07a4)

**Comment by rmlarsen** [comment]
Thanks for updating the bug @atondwal . FYI: I'm working on another change that will slightly improve performance and accuracy of erf().
