### ISSUE TITLE
`erfinv(1.)` should be `inf`

### ISSUE THREAD

**Issue by emilyfertig** [tensorflow/mlir-hlo#63]
`erfinv` was added in 221ac0e, and `erfinv(1.)` evaluates to a large positive float instead of `inf` (this surfaced in JAX when JAX 0.4.6 was released, and broke a test in TensorFlow Probability, comparing TF and JAX `erfinv`).

**Comment by atondwal** [comment]
Fixed by https://github.com/tensorflow/mlir-hlo/commit/fc1d3274d2c19de0c32f9fd0f446d81061222f92
