### ISSUE TITLE
`tiling_softmax.cc#tilePartialSoftmax: undefined reference to `mlir::gml_st::isSimpleBcastReduction'

### ISSUE THREAD

**Issue by makslevental** [tensorflow/mlir-hlo#65]
Compiling `mlir-hlo` as a dep of `torch-mlir` I get a linker error:

```
/usr/bin/ld: lib/libGmlStPasses.a(tiling_softmax.cc.o): in function `mlir::gml_st::(anonymous namespace)::tilePartialSoftmax(mlir::TilingInterface, mlir::PatternRewriter&, llvm::function_ref<mlir::FailureOr<mlir::TilingResult> (mlir::Operation*, long)>)':
undefined reference to `mlir::gml_st::isSimpleBcastReduction(mlir::Operation*, long*, mlir::gml_st::SimpleBcastReduction*)'
```

This symbol is at [gml_st/utils/linalg_utils.cc#L43](https://github.com/tensorflow/mlir-hlo/blob/master/gml_st/utils/linalg_utils.cc#L43).

Tracking it down, it seems [gml_st/transforms/CMakeLists.txt#L61](https://github.com/tensorflow/mlir-hlo/blob/master/gml_st/transforms/CMakeLists.txt#L61) depends on `MLIRGmlStUtils` but doesn't actually link it. 

cc @powderluv

**Comment by sherhut** [comment]
Should be fixed in https://github.com/tensorflow/mlir-hlo/commit/85dc21be838e0db63ea70737ea3634cb0131fdf7.
