### ISSUE TITLE
mhlo.dot inferred shape is incompatible with return type

### ISSUE THREAD

**Issue by seanmor5** [tensorflow/mlir-hlo#69]
I am working with mhlo in C++ for some external bindings. I have this code to add a dot operation to an existing function:

```c++
mlir::Value MLIRFunction::DotOp(mlir::Value lhs, mlir::Value rhs) {
  module_->builder()->setInsertionPointToEnd(&func_->getBody().back());
  mlir::ArrayAttr emptyPrecisionAttr = module_->builder()->getArrayAttr({});
  auto op = module_->builder()->create<mlir::mhlo::DotOp>(module_->builder()->getUnknownLoc(), lhs.getType(), lhs, rhs, emptyPrecisionAttr);
  return op;
}
```

This produces this mlir module:

```mlir
"builtin.module"() ({
  "func.func"() <{function_type = (tensor<1000000xf32>) -> tensor<1000000xf32>, sym_name = "main"}> ({
  ^bb0(%arg0: tensor<1000000xf32>):
    %0 = "mhlo.dot"(%arg0, %arg0) {precision_config = []} : (tensor<1000000xf32>, tensor<1000000xf32>) -> tensor<1000000xf32>
    "func.return"(%0) : (tensor<1000000xf32>) -> ()
  }) : () -> ()
}) : () -> ()
```

and trying to execute this results in this error:

```
** (RuntimeError) <unknown>:0: error: inferred shape '[]' is incompatible with return type of operation 'tensor<1000000xf32>'
```

Not sure why the shape inference is failing here

**Comment by seanmor5** [comment]
For additional context, I am using mhlo from a library built on top of openxla at commit c1e4a16e77a7ba2000003ccade3ffba3749ada35

**Comment by sdasgup3** [comment]
This seems to me a vector dot vector product whose result  should be a scalar with shape `[]`, which is what the diagostic message is suggesting. 

Please refer to [ref](https://github.com/openxla/stablehlo/blob/d865f3f8a32cf50458bcf300be3392b3e2fcb95a/stablehlo/dialect/TypeInference.cpp#L1855) for the origin of error.

**Comment by seanmor5** [comment]
Hi @sdasgup3 thank you for the response. I realized I was passing one of the arg types as the return type for the function; however, even after resolving that it does not fix the issue. This is what the module looks like:

```mlir
"builtin.module"() ({
  "func.func"() <{function_type = (tensor<1000000xf32>) -> f32, sym_name = "main"}> ({
  ^bb0(%arg0: tensor<1000000xf32>):
    %0 = "mhlo.dot"(%arg0, %arg0) {precision_config = []} : (tensor<1000000xf32>, tensor<1000000xf32>) -> tensor<1000000xf32>
    "func.return"(%0) : (tensor<1000000xf32>) -> ()
  }) : () -> ()
}) : () -> ()
```
Notice:

```mlir
    %0 = "mhlo.dot"(%arg0, %arg0) {precision_config = []} : (tensor<1000000xf32>, tensor<1000000xf32>) -> tensor<1000000xf32>
```

This is generated from C++, so I'm not specifying the return for the dot product anywhere. I'm not sure why the generated module says the output should be a tensor with that shape

**Comment by sdasgup3** [comment]
>>  realized I was passing one of the arg types as the return type for the function; however, even after resolving that it does not fix the issue. 
Do you mind showing how you resolved it? Maybe you can share the arguments to ` module_->builder()->create<mlir::mhlo::DotOp>`

**Comment by seanmor5** [comment]
In this instance I just ended up just changing the return type to my function to something like `mlir::FloatType::getF32(context)`.

I can try to write a C++ reproducer, but right now I'm doing everything from Elixir with NIFs. The program looks like this:

```elixir
arg_xla_shape = EXLA.Shape.make_shape({:f, 32}, {1_000_000})
arg_xla_ret_shape = EXLA.Shape.make_shape({:f, 32}, {})
mlir_arg_types = Enum.map([arg_xla_shape], &EXLA.MLIR.Type.new/1)
mlir_ret_type = EXLA.MLIR.Type.new(arg_xla_ret_shape)

module = EXLA.MLIR.Module.new()
function = EXLA.MLIR.Module.create_function(module, "main", mlir_arg_types, mlir_ret_type)
[arg] = EXLA.MLIR.Function.get_arguments(function)

result = EXLA.MLIR.Value.dot(arg, arg)

:ok = EXLA.NIF.mlir_build(function.ref, result.ref)
EXLA.NIF.dump_mlir_module(module.ref)
```

Functions are created like this and returned as references to Elixir:

```c++
MLIRFunction * MLIRModule::CreateFunction(
  std::string name,
  std::vector<std::pair<std::vector<tsl::int64>, int>> arg_types,
  std::pair<std::vector<tsl::int64>, int> ret_type
) {
  std::vector<mlir::Type> types;
  types.reserve(arg_types.size());
  for (auto arg_type : arg_types) {
    mlir::Type type = GetMLIRType(builder_.get(), arg_type.first, arg_type.second);
    types.push_back(type);
  }

  mlir::Type return_type = GetMLIRType(builder_.get(), ret_type.first, ret_type.second);

  auto funcType = builder_->getFunctionType(types, return_type);
  auto loc = builder_->getUnknownLoc();
  auto funcOp = std::make_unique<mlir::func::FuncOp>(mlir::func::FuncOp::create(loc, name, funcType));
  module_->push_back(*funcOp);
  funcOp->addEntryBlock();
  builder_->setInsertionPointToStart(&funcOp->getBody().front());
  return new MLIRFunction(this, std::move(funcOp));
}
```

In this case types and return_type are resolved from the MLIR type above which passes the dimension and type to the NIF. 

Then I return all arguments to the runtime:

```c++
llvm::MutableArrayRef<mlir::BlockArgument> get_arguments() { return func_->getBody().front().getArguments(); }
```

And then resolve those as `mlir::Value` for operations. `build` just adds the Func ReturnOp to the function. So in this case the arguments to `module_->builder()->create<mlir::mhlo::DotOp>` are just the block arguments to the function. They both have shape 1000000xf32

**Comment by seanmor5** [comment]
Ah sorry I am new to MLIR and was confusing the nomenclature "type" for element type instead of representing a shape (both dimension numbers and element type). So I am indeed incorrectly specifying the return type of the dot operation. Is there a way to specify an unknown return type in this case? I'm trying something like this now, but getting a similar error:

```elixir
mlir::Value MLIRFunction::DotOp(mlir::Value lhs, mlir::Value rhs) {
  module_->builder()->setInsertionPointToEnd(&func_->getBody().back());
  mlir::ArrayAttr emptyPrecisionAttr = module_->builder()->getArrayAttr({});
  mlir::Type type = lhs.getType();
  mlir::Type elementType = type.cast<mlir::TensorType>().getElementType();
  mlir::UnrankedTensorType unrankedTensorType = mlir::UnrankedTensorType::get(elementType);
  auto op = module_->builder()->create<mlir::mhlo::DotOp>(module_->builder()->getUnknownLoc(), unrankedTensorType, lhs, rhs, emptyPrecisionAttr);
  return op;
}
```

**Comment by sdasgup3** [comment]
Can you please try this out instead?
```
auto rankZeroTensorType  = mlir::RankedTensorType::get({}, elementType);
```

**Comment by seanmor5** [comment]
That indeed works! Is there a way to avoid that though? My goal is to not have to hard code the shape or have to do shape calculations myself. If there's no path around it then no big deal, just curious
